name: test-pre-python

on:
  workflow_dispatch: # manual invocation

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12-dev"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: matrix.os
    steps:
      - uses: actions/checkout@v3
        with:
          ref: github.ref